modLoader="javafml"
loaderVersion="[1.21,)"
license="MIT"

[[mods]]
modId="toolswapper"
version="1.0"
displayName="Tool Swapper Mod"
description="Automatically replaces tools when they break."
logoFile="logo.png"
authors="Stefan Bogdanovic"
credits="I needed this for AFKing."
displayURL="https://github.com/stefanbogdanov2c/minecraft-forge-tool-swapper"
issueTrackerURL="https://github.com/stefanbogdanov2c/minecraft-forge-tool-swapper/issues"

# Optional dependencies section
# [dependencies.toolswapper]
# modId="forge"
# mandatory=true
# versionRange="[1.21,)"
# ordering="NONE"
# side="BOTH"
